### ISSUE TITLE
Clipboard monitor window can be resized vertically

### ISSUE THREAD

**Issue by Perelandra0x309** [humdingerb/clipdinger#13]
Did you want the Clipboard monitor window to be resizable only horizontally?  When resizing vertically it just exposes empty sapce below the instructions.

Or did you mean for the replicant to be able to have multiple entries of history?  That would be cool, if the replicant could be expanded vertically to show the last 5, 10, whatever entries in history.

**Comment by humdingerb** [comment]
No, the replicant stands alone, apart from the rest of Clipdinger and is only supposed to show the current clipboard contents. I briefly considered making the whole history list into a replicant.
I decided against it, because the replicant has to be visible on the screen to be useful. While that's possible with a one-liner, esp. on the right side of the screen where it won't be often obscured because of the yellow tab of windows leaving that space open, for several lines that's increasingly not the case.
Also, in my modus operandi, I use Clipdinger almost exclusively by keyboard. I'm already entering text and instead of ALT+C, I press SHIFT+ALT+C to insert from history.

To the core of this issue: The replicant is supposed to be made almost arbitrarily narrow. If it gets very narrow, the instructions line-break and the window has to be able to resize vertically to make it readable again. Most users probably won't bother, having red them once when first opening the window, but it's nicer than to just have a fixed vertical size.

Thanks for the note though.

**Comment by Perelandra0x309** [comment]
Ah I see what you mean about resizing the window. How about using a split view to resize the replicant?  Or use a tooltip?

**Comment by humdingerb** [comment]
It's possible, of course. I don't see a significant gain, though, only to be able to restrict the resizing vertically. A spliview has the small inconvenience, that if you wanted to make the replicant view wider, you'd have to resize the window first, then maybe make it smaller again with the split handle. Can use just the window for resizing from the start.
A tooltip would work of course, but normally I'd use a tooltip for infos that otherwise would clutter the GUI. In this case, it doesn't and it's immediately discoverable other than with a tooltip, where the user might take some time trying to figure out what this is before getting the idea that there might be tooltip.
