### ISSUE TITLE
App crashes when trying to change a title in favourites

### ISSUE THREAD

**Issue by Akujiism** [humdingerb/clipdinger#2]
- add clip to favourites
- select 'Edit Title'
Result: the app crashes (see the report in attachment)
The issue can't be reproduced in 100% of cases but I get it around 2 times out of 5 tries.

[Clipdinger-782-debug-23-05-2016-21-52-29.zip](https://github.com/humdingerb/clipdinger/files/278992/Clipdinger-782-debug-23-05-2016-21-52-29.zip)

**Comment by humdingerb** [comment]
I think I found the bug. It crashes if there isn't a favourite selected, when the "Edit title" is invoked. That shouldn't be easily possible, because you do that from a context menu on that favourite... I could emulate with sending the message via "hey".   
Until I've fixed the bug, try to make sure you have a favourite selected when editing its title... :)   
Thanks!

**Comment by humdingerb** [comment]
Fixed with 4088d455115ed84dfd89ee8699e27b6374af689a.
