### ISSUE TITLE
Folders to organize clips

### ISSUE THREAD

**Issue by ojasva** [humdingerb/clipdinger#24]
Add folder and sub-folder support to clips, could be a nice way to organize clips.

Example:

Folder - Emails
             hello@example.com
             info@example.com
             me@example.com
Folder - Nursery Rhymes
             Baba Black Sheep
             Jonny! Jonny! Yes Papa...
Folder - URLS
             google.com

etc

The user would have the power to create folders and sub folder as per his requirements.

**Comment by humdingerb** [comment]
If implemented, I'd suggest to only do this for the favorites. The clip list at the left is really meant as a fleeting history of clips. I'll rename the topic accordingly.

Instead of expanding/collapsing groups, I could imagine having several tabs with sets of favorites being better. Then you can select a different tab for different projects...

Not sure people keep that many favourites around. Maybe poll the Clipdinger users before implementing. It's not just a lot of work, but also impacts the clean GUI.
Could very well be feature creep... :)

**Comment by humdingerb** [comment]
> Not sure people keep that many favourites around. Maybe poll the Clipdinger users before implementing. It's not just a lot of work, but also impacts the clean GUI.
Could very well be feature creep... :)

It is. Closing. :)
