### ISSUE TITLE
Extend support for files

### ISSUE THREAD

**Issue by ojasva** [humdingerb/clipdinger#25]
When a user copies a Image/HTML File/anyfile for that matter. It would solve the same problem. 
i.e you often have to paste some file you've just recently copied, but that has been replaced by something you've copied more recently.

**Comment by humdingerb** [comment]
I'm not sure that is an often encountered use-case. I also imagine it difficult to implement: We can't just save a copy of the last 100 or whatever copied/cut files, as they may be huge. We probably want to only save the file+path. And here we should go with the pasted location, because in case a file was cut instead of copied it won't be there anymore...

I expect all this is only remotely possible, if the app can get all the needed info from Tracker. Not sure this is possible.

I tend to think this kind of usage of Clipdinger is out of its intended scope...
